### ISSUE TITLE
Merge with TrustedProxy?

### ISSUE THREAD

**Issue by IlCallo** [jdavidbakr/CloudfrontProxies#1]
This is really helpful (we had the same problem for a project of ours), do you mind taking contacts to the TrustedProxy maintainer, which is discussing similar problems  (https://github.com/fideloper/TrustedProxy/issues/108), and try to merge the packages in a way which allows custom headers in general, with shortcuts for more common setups?

**Comment by jdavidbakr** [comment]
I'm glad this is helpful!  I'm not opposed to having this get merged into the TrustedProxy code or at least the concept being imported into it; my code is pretty Laravel-specific, though, I don't know enough about the raw Symfony structure to know how to hook this into that.  Hopefully Symfony will make it all irrelevant soon by giving us access to these headers again.

**Comment by IlCallo** [comment]
Well, TrustedProxy is Laravel-specific too so there should not be any problem, obviously we are talking about a workaround until Symfony works it out ;)
Let's see what the TustedProxy mantainer thinks about this...

**Comment by jdavidbakr** [comment]
Oh, you're right, for some reason I was thinking it was one step removed from Laravel.

**Comment by fideloper** [comment]
I'd love to see if Symfony has some hidden way (or maybe will accept a PR) to once again allow a few other headers. I'm hitting this issue as well! (I like this implementation also - I wonder how often their IP addresses change!?)

**Comment by fideloper** [comment]
Here's how I solved it in Nginx.

**My setup:**

Cloudfront -> Nginx -> [Docker container with Nginx + PHP-FPM]. I have an extra layer in there, but this still applies.

The docker container is listening on port `8080`.

```
upstream app {
    server 127.0.0.1:8080;
}

map $http_cloudfront_forwarded_proto $cloudfront_proto {
    default "http";
    https "https";
}

server {
    listen 80 default_server;

    root /var/www/html;

    index index.html index.htm;

    server_name front.example.org;

    charset utf-8;

    location / {
        include proxy_params;
        proxy_set_header X-Forwarded-Proto $cloudfront_proto;
        proxy_pass http://app;
        proxy_redirect off;

        # Handle Web Socket connections
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
```

This use of `map` gets around weirdness with Nginx and `if` conditionals.

It sets a variable `$cloudfront_proto` to "http" by default. If `$http_cloudfront_forwarded_proto` exists and has value "https", then $cloudfront_proto gets value `https`.

We then set header `X-Forwarded-Proto` to `$cloudfront_proto`.

**Caveats**

1. Header `X-Forwarded-Proto` will become set to `http` even if an X-Forwarded-Proto is sent along in the request (In my setup, I know it will always be cloudfront, but not everyone can guarantee that)
2. You may receive the following warning if you do not also comment out the `X-Forwared-Proto` header set in `/etc/nginx/proxy_params`:

> nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size

**Edit** Actually this format will take both headers into account, with a preference toward `https` is either is set to that.

```
map "$http_cloudfront_forwarded_proto:$http_x_forwarded_proto" $cloudfront_proto {
    default "http";
    ":http" "http";
    ":https" "https";
    "http:" "http";
    "https:" "https";
    "https:http" "https";
    "http:https" "https";
}
```

**Comment by jdavidbakr** [comment]
I saw that in one of the issues threads, but I don't like decoupling this logic from the app.  I try to keep my apps so that they deploy with minimal extra configuration in nginx or apache.  I agree, though, it would be ideal if Symfony would include the ability to directly specify CloudFront.

**Comment by fideloper** [comment]
Right on, just saying in case it's helpful to anyone 👍

**Comment by IlCallo** [comment]
The issue I opened on symfony repo has been labelled as "feature" (https://github.com/symfony/symfony/issues/26333), consider going there and leaving a comment of your own or a thumb up to the first comment, maybe that could help 🤔
