### ISSUE TITLE
Must configure CloudFront to set Cloudfront-Forwarded-Proto

### ISSUE THREAD

**Issue by hmoffatt** [jdavidbakr/CloudfrontProxies#2]
readme.md implies that you only need to enable this code in your Laravel middleware configuration, but you also have to configure CloudFront to actually set Cloudfront-Forwarded-Proto (in Behaviours - Whitelist headers). It doesn't set it by default, and then the middleware doesn't detect the request as coming from Cloudfront.

In my case I don't need X-Forwarded-Proto to be set properly, as I'm using https everywhere. I think it would be better to test for X-Amz-Cf-Id to be sure it's a Cloudfront request than to look for Cloudfront-Forwarded-Proto.

Either way the doc should mention that you have to manually set up this header.

Thanks for the code!

**Comment by jdavidbakr** [comment]
Thanks for the comments, I've updated the readme.
