### ISSUE TITLE
Hardcoded HEADER_X_FORWARDED_ALL Constant

### ISSUE THREAD

**Issue by TheoKouzelis** [jdavidbakr/CloudfrontProxies#3]
Hello @jdavidbakr 

Thanks for writing this package.

Looking at the code I've noticed the [HEADER_X_FORWARDED_ALL is hard coded ](https://github.com/jdavidbakr/CloudfrontProxies/blob/b9cba239578056fe60f7bea39ee6c996d2988ae5/src/CloudfrontProxies.php#L45) into the middleware. Is this required for the package to work? 

Would it be better to follow a similar pattern to Fidelopers Trusted Proxy middleware to set the [constant in a class variable](https://github.com/fideloper/TrustedProxy/blob/master/src/TrustProxies.php#L30) which then the [user can extend and overwrite](https://github.com/laravel/laravel/blob/8.x/app/Http/Middleware/TrustProxies.php#L22) according to their needs.

I've also seen that Symfony are deprecating the HEADER_X_FORWARDED_ALL in version [5.2 of their HTTP package]( https://github.com/symfony/http-foundation/blob/5.x/Request.php#L589)

Happy to create a PR if you broadly agree?

**Comment by jdavidbakr** [comment]
I think a better option would be to create a config file that the user could publish and modify as needed.  I'd be willing to look at a PR that does that.

**Comment by jdavidbakr** [comment]
Newest version has config file
